# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_auto_20170610_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='facebook',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
