# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_articulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='creado',
        ),
    ]
