# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_remove_person_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='facebook',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_media'),
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
