# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 06:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_person_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=datetime.date(2017, 5, 28)),
            preserve_default=False,
        ),
    ]
