# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_person_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='genero',
            field=models.CharField(choices=[('1', 'Hombre'), ('2', 'Mujer')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
