# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nacionalidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Nacionalidad'),
            preserve_default=False,
        ),
    ]
