# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_person_nacionalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birthday',
        ),
        migrations.AddField(
            model_name='person',
            name='facebook',
            field=models.CharField(default=8, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='twitter',
            field=models.CharField(default=8, max_length=40),
            preserve_default=False,
        ),
    ]
