# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_auto_20170610_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha de creacion del registro', verbose_name='Fecha de creacion'),
            preserve_default=False,
        ),
    ]
