# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_auto_20170610_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='autor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
