# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 00:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_auto_20170611_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='autor',
            field=models.ForeignKey(default=1, help_text='Quien guarda el registro', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que guardo'),
            preserve_default=False,
        ),
    ]
