# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_auto_20170611_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Person'),
        ),
    ]
